openapi: 3.0.3
info:
  title: Soyio API
  description: |-
    Soyio Identity Service API
  contact:
    email: soporte@soyio.id
  version: 1.0.0
externalDocs:
  description: Más información acerca de Soyio
  url: http://soyio.id
servers:
  - url: https://sandbox.soyio.id/api/v1
  - url: https://app.soyio.id/api/v1
tags:
  - name: identity
    description: Identidades
paths:
  /identities:
    get:
      tags:
        - identity
      summary: Get all identities
      description: Multiple status values can be provided with comma separated strings
      operationId: indexIdentities
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Identity'          
        '400':
          description: Invalid status value
      security:
        - api_key: []
  /identities/{identity_id}:
    get:
      tags:
        - identity
      summary: Get specific Identity by ID
      operationId: getIdentity
      parameters:
        - name: identity_id
          in: path
          description: Identity ID to find
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'          
        '400':
          description: Invalid tag value
      security:
        - api_key: []
components:
  schemas:
    IdentityInformation:
      type: object
      properties:
        key:
          type: string
          example: "name"
        value:
          type: string
          example: "Jon"
      xml:
        name: tag
    Identity:
      type: object
      properties:
        id:
          type: string
          example: 'id_ma21KLsmaslopask912Aa2'
        email:
          type: string
          example: jonsnow@nightswatch.com
        data:
          type: array
          items:
            $ref: '#/components/schemas/IdentityInformation'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Identity'
        application/xml:
          schema:
            $ref: '#/components/schemas/Identity'
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header