openapi: 3.0.3
info:
  title: Soyio API
  description: |-
    Soyio Identity Service API proporciona servicios de gestión de identidades digitales para autenticación y autorización de usuarios. Permite a los desarrolladores integrar y gestionar identidades de usuario de forma segura en sus aplicaciones.
  contact:
    email: soporte@soyio.id
  version: 1.0.0
externalDocs:
  description: Más información acerca de Soyio
  url: http://soyio.id
servers:
  - url: https://sandbox.soyio.id/api/v1
  - url: https://app.soyio.id/api/v1
tags:
  - name: identity
    description: Operaciones relacionadas con la gestión de identidades de usuario.
paths:
  /identities:
    get:
      tags:
        - identity
      summary: Obtener todas las identidades
      description: Retorna una lista de todas las identidades registradas.
      operationId: indexIdentities
      responses:
        '200':
          description: Operación exitosa, retorna una lista de identidades.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Identity'
        '400':
          description: Valor de estado inválido
      security:
        - api_key: []
  /identities/{identity_id}:
    get:
      tags:
        - identity
      summary: Obtener identidad específica por ID
      operationId: getIdentity
      parameters:
        - name: identity_id
          in: path
          description: ID de la identidad que se quiere encontrar.
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa, retorna la identidad solicitada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
        '400':
          description: Valor de ID inválido
      security:
        - api_key: []
components:
  schemas:
    IdentityInformation:
      type: object
      properties:
        key:
          type: string
          example: "name"
        value:
          type: string
          example: "Jon"
      xml:
        name: tag
    Identity:
      type: object
      properties:
        id:
          type: string
          example: 'id_ma21KLsmaslopask912Aa2'
        email:
          type: string
          example: jonsnow@nightswatch.com
        data:
          type: array
          items:
            $ref: '#/components/schemas/IdentityInformation'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Identity:
      description: Objeto Identity que necesita ser creado o actualizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Identity'
        application/xml:
          schema:
            $ref: '#/components/schemas/Identity'
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
